netInterface: wlp3s0
usersFilePath: users.yaml
mqttBroker: mqtt://huey:qwftyrsi@192.168.1.15
netmask: 255.255.255.0
gateway: 192.168.1.1
certificatePath: cert2
timezone: Europe/Stockholm
httpPort: 8888
httpsPort: 8443


